### ISSUE TITLE
Memory increases during generation and does not decrease afterwards

### ISSUE THREAD

**Issue by wuarmin** [caxlsx/caxlsx#157]
Hey,
I create some spreadsheets in sidekiq. I observe a RAM-usage increase during xlsx-generations. That's ok, but the memory does not decrease afterwards. Does somebody has a hint? What can I do. 

My spreadsheet generation pseude code looks like this:
```ruby
xlsx = Axlsx::Package.new

workbook = xlsx.workbook
sheet = workbook.add_worksheet(name: "Export")

# add rows
row_styles = get_row_styles
get_rows.each do |row| # get rows with limit offset from db
  sheet.add_row(get_row_values(row), style: row_styles)
end

xlsx.serialize("public/xlsx_exports/file.xlsx")
```
![image](https://user-images.githubusercontent.com/9987680/182647436-4b81bc20-02e7-4b38-9091-9228bef7cb81.png)

I found this: https://www.rubydoc.info/gems/caxlsx/Axlsx%2FRelationship%2Eclear_ids_cache
Do I have to use this?
Thank you in advance!

**Comment by kiskoza** [comment]
Hi. Thanks for the report. I assume you're using the latest version (v3.2.0), please correct me otherwise.

You don't need to call `clear_ids_cache` manually, if you check [serialize](https://github.com/caxlsx/caxlsx/blob/v3.2.0/lib/axlsx/package.rb#L103-L118) or [to_stream](https://github.com/caxlsx/caxlsx/blob/v3.2.0/lib/axlsx/package.rb#L124-L133), you can see that the code already calls it for you (even if there's an error during the method calls).

First, I would try to call for a manual garbage collection to see if it's really a leak or juts a lazy GC, something like this:

```ruby
xlsx = Axlsx::Package.new
# add rows, etc
xlsx.serialize("path/to/file")

xlsx = nil # to remove reference. this happens anyway when you return from the method where it was initialized
GC.start
```

Next, I would check `get_rows` and `get_row_values`. Does the memory bloat go away if you skip the xlsx generation, but run all the other codes? I would check the memory footprint of this code:

```ruby
def without_xlsx
  get_row_styles
  get_rows.each do |row|
    get_row_values(row)
  end
end
```

Finally, if there's a memory leak with a bunch of data (on prod), then it should cause a memory leak with less data too, you just need to run it more times to see the impact. There are a few tools that can help you figure out what's causing it, like [memory_profiler](https://github.com/SamSaffron/memory_profiler), [ruby-prof](https://github.com/ruby-prof/ruby-prof) or [derailed_benchmarks](https://github.com/zombocom/derailed_benchmarks)

**Comment by wuarmin** [comment]
@kiskoza Thank you for your help. The memory consumption issue had nothing to do with **caxlsx** **gem**. It was indeed an issue in the `get_rows`-function. I spent several hours trying to find the leak with the help of `memory_profiler` and this helpful [post](http://stratus3d.com/blog/2020/08/11/effective-debugging-of-memory-leaks-in-ruby/). I fixed my specific issue with a code change (switched to another method to load the sql-relation), but I could not find out yet, what's the problem with the initial code. What puzzles me is that it only seems to happen when the code is running in sidekiq. I would have liked to find the reasons and then report this issue to the appropriate projects (rom-rb, sequel), but I need to close this case for now.
