### ISSUE TITLE
Add style to all cells in the column

### ISSUE THREAD

**Issue by luisgmartins** [caxlsx/caxlsx#159]
When a style is added for an entire column it is only applied to cells that have been added to the sheet. This means that I have to set all cells to nil if I want to generate a styled xlsx file so that whoever fills it in will have the data in the correct format.
It would be interesting to have the styles applied to the entire column in the same way as the validations.

**Comment by noniq** [comment]
This would be an nice feature to have (if possible). Anyone willing to investigate?

**Comment by westonganger** [comment]
I took a stab at reverse engineering this and wasnt able to figure this out looking at the xml contents there. Maybe there is something I am missing on reverse-engineering for xlsx spreadsheets. If there isnt a guide/toolbox then maybe we should have one, to support people wanting to help add features.

I just used `tar -xf my_spreadsheet.xlsx` and started looking at the XML contents.

**Comment by Grasseh** [comment]
I've needed this for a project I'm working on.
In case someone needs to fiddle with this in the future and ends up here:

Excel columns can include a relationship towards a <cellXfs> define in the stylesheet, referencing the index. Below is a stripped-down example of a stylesheet of a file I've generated using the library:

```
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<numFmts count="3">
<numFmt numFmtId="100" formatCode="yyyy/mm/dd"/>
<numFmt numFmtId="101" formatCode="yyyy/mm/dd hh:mm:ss"/>
<numFmt numFmtId="102" formatCode="@"/>
</numFmts>
<fonts count="2">...
</fonts>
<fills count="3">...
</fills>
<borders count="3">...
</border>
<border>...
</borders>
<cellStyleXfs count="1">
<xf borderId="0" numFmtId="0" fontId="0" fillId="0"/>
</cellStyleXfs>
<cellXfs count="5">
<xf borderId="0" numFmtId="0" fontId="0" fillId="0" xfId="0"/>
<xf borderId="1" numFmtId="0" fontId="0" fillId="0" xfId="0"/>
<xf borderId="0" numFmtId="14" fontId="0" fillId="0" xfId="0" applyNumberFormat="1"/>
<xf borderId="2" numFmtId="0" fontId="1" fillId="2" applyNumberFormat="0" applyFill="1" applyFont="1" applyBorder="1" applyAlignment="1" applyProtection="0">
<alignment horizontal="center" vertical="center"/>
</xf>
<xf borderId="0" numFmtId="102" fontId="0" fillId="0" applyNumberFormat="1" applyFill="0" applyFont="0" applyBorder="0" applyAlignment="0" applyProtection="0"/>
</cellXfs>
<cellStyles count="1">
<cellStyle name="Normal" xfId="0"/>
</cellStyles>
<dxfs count="0"/>
<tableStyles defaultTableStyle="TableStyleMedium9" defaultPivotStyle="PivotStyleLight16" count="0"/>
</styleSheet>
```

The last cellXfs was the one I was attempting to assign to a column. It turns out, Excel does support this. So while Caxlsx generates this following sheet1.xml:

```
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xml:space="preserve">
<sheetPr>
<pageSetUpPr fitToPage="0"/>
</sheetPr>
<dimension ref="A1:N1"/>
<sheetViews>...
</sheetViews>
<sheetFormatPr baseColWidth="8" defaultRowHeight="18"/>
<cols>
<col min="1" max="1" bestFit="1" customWidth="1" width="15"/>
<col min="2" max="2" bestFit="1" customWidth="1" width="15"/>
<col min="3" max="3" bestFit="1" customWidth="1" width="15"/>
<col min="4" max="4" bestFit="1" customWidth="1" width="15"/>
<col min="5" max="5" bestFit="1" customWidth="1" width="15"/>
<col min="6" max="6" bestFit="1" customWidth="1" width="15"/>
<col min="7" max="7" bestFit="1" customWidth="1" width="15"/>
<col min="8" max="8" bestFit="1" customWidth="1" width="15"/>
<col min="9" max="9" bestFit="1" customWidth="1" width="15"/>
<col min="10" max="10" bestFit="1" customWidth="1" width="15"/>
<col min="11" max="11" bestFit="1" customWidth="1" width="15"/>
<col min="12" max="12" bestFit="1" customWidth="1" width="15"/>
<col min="13" max="13" bestFit="1" customWidth="1" width="15"/>
<col min="14" max="14" bestFit="1" customWidth="1" width="15"/>
</cols>
<sheetData>...
</sheetData>
...
</worksheet>
```

We can modify the col property to apply a cellXfs style by simply adding style=index where index is a string representing the index of the style in the cellXfs array. Thankfully, caxlsx already provides that when adding a style to a workbook.

The desired end result for mewould look like this:

```
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xml:space="preserve">
<sheetPr>
<pageSetUpPr fitToPage="0"/>
</sheetPr>
<dimension ref="A1:N1"/>
<sheetViews>...
</sheetViews>
<sheetFormatPr baseColWidth="8" defaultRowHeight="18"/>
<cols>
<col min="1" max="1" bestFit="1" customWidth="1" width="15"/>
<col min="2" max="2" bestFit="1" customWidth="1" width="15"/>
<col min="3" max="3" bestFit="1" customWidth="1" width="15"/>
<col min="4" max="4" bestFit="1" customWidth="1" width="15"/>
<col min="5" max="5" bestFit="1" customWidth="1" width="15"/>
<col min="6" max="6" bestFit="1" customWidth="1" width="15"/>
<col min="7" max="7" bestFit="1" customWidth="1" width="15"/>
<col min="8" max="8" bestFit="1" customWidth="1" width="15"/>
<col min="9" max="9" bestFit="1" customWidth="1" width="15"/>
<col min="10" max="10" bestFit="1" customWidth="1" width="15"/>
<col min="11" max="11" bestFit="1" customWidth="1" width="15"/>
<col min="12" max="12" bestFit="1" customWidth="1" width="15" style="4"/>
<col min="13" max="13" bestFit="1" customWidth="1" width="15" style="4"/>
<col min="14" max="14" bestFit="1" customWidth="1" width="15"/>
</cols>
<sheetData>...
</sheetData>
...
</worksheet>
```

Thankfully, there is a way to toy around with the library to end up with this desired result as well. It's not well-intended, as playing with instance variables means that things could easily change in the future, but this shows that this library is able to produce this desired result on the current version.

What needs to be done to apply the style on both columns indexed at 12 and 13 is as follows:

```
style = package.workbook.styles.add_style(
  format_code: '@'
)

[12, 13].each do |index|
  package
    .workbook
    .worksheets
    .first
    .column_info
    .instance_variable_get('@list')[index]
    .style = format_style
```

I do not have time to play with the classes and interfaces in the library to implement a more direct and maintainable path to support this, but I hope this reverse-engineering provides enough information to assist someone that needs this exact feature or that is more familiar with this gem's codebase to implement it (because creating 100000 rows to apply the style on it for a template takes way too long for users).
