### ISSUE TITLE
Unable to group columns and rows in sheets

### ISSUE THREAD

**Issue by stathis-alexander** [caxlsx/caxlsx#344]
I believe this is an issue with caxlsx, but it may also be in how we're using it. I can't tell. When we generate excel documents with caxlsx, we are unable to group rows or columns in excel. The group appears to get added, but the columns are not hidden and cannot be expanded or contracted. 

If I manually add a new sheet to an existing document generated with caxlsx, grouping columns works as expected in the new sheet.

**Comment by stathis-alexander** [comment]
Certainly. Thanks for taking the time, and sorry my original post was lacking in detail. 

Here's a snippet to generate a file:
```
document = Axlsx::Package.new

document.workbook.add_worksheet(name: 'test_sheet') do |sheet|
  sheet.sheet_view.show_grid_lines = false
  sheet.add_row(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
  sheet.add_row(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
  sheet.add_row(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
  sheet.add_row(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
  sheet.add_row(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
end

file = Tempfile.new('test_file.xlsx', "#{Rails.root}/tmp", encoding: 'ASCII-8BIT')
begin; file.write(document.to_stream.read); ensure; file.close; end
```

I've attached a copy of the file it generates here: [tempfile.xlsx](https://github.com/caxlsx/caxlsx/files/14039775/tempfile.xlsx)

Here is a [loom](https://www.loom.com/share/9c1cd2d1b80b4cb983aae3a8fa72d51d?sid=e174e728-36d2-4f0d-ac1c-ac5105772b38) I recored outlining both the issue and the expected behavior in the document I generated using this snippet and attached above.

**Comment by kiskoza** [comment]
Thanks for the details! I was able to reproduce the issue and found out what's missing. There's an option to show or hide the outline symbols for the worksheets:

![image](https://github.com/caxlsx/caxlsx/assets/1900366/756ba9d2-e03d-41c8-ae67-f12c80311ffe)

It looks like the deafault value for new sheets is `true`, but we're treating it as `false` by default.

https://github.com/caxlsx/caxlsx/blob/333331d54639685046d0aeb11a605a729edba656/lib/axlsx/workbook/worksheet/sheet_view.rb#L33-L42

The quick solution for your problem is changing the value to be true

```ruby
sheet.sheet_view.show_outline_symbols = true
```

----

On the long term, we should change the default value to reflect how Excel usually works. After a quick poking around, it doesn't look like a breaking change to me.

1. If the file has outlines / groups, then we already toggle the flag (see [this line](https://github.com/caxlsx/caxlsx/blob/v4.0.0/lib/axlsx/workbook/worksheet/worksheet.rb#L749)) - if somebody doesn't want it to be visible, they already have a code to hide the symbols.
2. If the file does not have outlines / groups, then it's an invisible change for the end users.
3. The only problematic workflow I can imagine is when the developer wants to "break" this feature wittingly to have the same results as in the Loom video and relies on the default value we currently have. Even in this scenario the user can go into the File > Options > Advanced and set it back to normal.

What do you think? Should we change the defaults here?

**Comment by stathis-alexander** [comment]
> The quick solution for your problem is changing the value to be true
```
sheet.sheet_view.show_outline_symbols = true
```

Thank you so much! I will make this update to our local code. 

> What do you think? Should we change the defaults here?

My expectation, which may be different from others, is that a document generated by AXLSX, without any explicit manipulations to the contrary, would operate identically to a newly created excel document from the UI. Anything otherwise feels a bit like a foot gun: I may generate and distribute a bunch of sheets expecting them to work like a fresh document and find out otherwise. 

> The only problematic workflow I can imagine is when the developer wants to "break" this feature wittingly to have the same results as in the Loom video and relies on the default value we currently have.

I agree. This feels like a breaking change given that there may be those out there relying on this assumption.

Happy to submit a PR to update this default value if we feel the risk is worth the reward.

**Comment by kiskoza** [comment]
I think it's more like a bug we need to fix, not a feature we'll break with the code change. Feel free to create a PR

**Comment by stathis-alexander** [comment]
Done: https://github.com/caxlsx/caxlsx/pull/345. Thank you so much for your help here.
