### ISSUE TITLE
Leftovers from 1.8.7

### ISSUE THREAD

**Issue by tagliala** [caxlsx/caxlsx#371]
https://github.com/caxlsx/caxlsx/blob/5fa52de0f48591e6424ed3e60848b75ac82fb9bb/lib/axlsx/stylesheet/styles.rb#L329

Commit: 55a0dd9d3b522876dc97e109b2d38b261cdaf752

https://github.com/caxlsx/caxlsx/blob/5fa52de0f48591e6424ed3e60848b75ac82fb9bb/lib/axlsx/util/serialized_attributes.rb#L95

Commit: bc256511fc600030746206f25b25d18385f5f2c2

The latter is not clear to me

**Comment by tagliala** [comment]
keep open?

**Comment by noniq** [comment]
Keeping open because of https://github.com/caxlsx/caxlsx/blob/5fa52de0f48591e6424ed3e60848b75ac82fb9bb/lib/axlsx/util/serialized_attributes.rb#L95 ?

For me it looks like this change (https://github.com/caxlsx/caxlsx/commit/bc256511fc600030746206f25b25d18385f5f2c2) at a whole was not specific to/for 1.8.7, only the choice of using an array instead of a hash was. But eventhough Ruby as ordered hashes now I’m not sure if it would be worth the effort to change the code to use a hash instead. What do you think?

**Comment by kiskoza** [comment]
I don't think it worth refactoring at this point, the resoning behind it being an array makes sense (easier to remember that the order of the elements would matter in an array than a hash...), so let's just remove that part of the comment.

Also I looked into what this method does, and we never call it with the mentioned `additional_attributes` params :upside_down_face:

**Comment by tagliala** [comment]
Closed by #391
