### ISSUE TITLE
Ruby version update proposal

### ISSUE THREAD

**Issue by olhor** [caxlsx/caxlsx#48]
Don't you think that changing ruby version requirement from 1.9.2 to 2.3 as a "fix" (3.0.0 -> 3.0.1) is a bit thoughtless...

**Comment by simi** [comment]
Yeah, 3.0.0 release, it was a little chaotic at that time. Please consider 3.0.1 as first proper 3.0.1 release. I think there's not a much we can do about that now except yanking 3.0.0, which is not probably good idea :/.

Ruby 1.9 was actually not supported since https://github.com/randym/axlsx/commit/1d030fb4eb60cd55d5ec9d92c42bb63d52527bfc#diff-354f30a63fb0907d4ad57269548329e3. What has happened in 3.0.0 -> 3.0.1 was more gemspec bugfix since 1.9 wasn't officially supported already for years. Same works for following ruby versions up to 2.2.

**Comment by olhor** [comment]
I'm still on ruby 2.1 so good to have version 3.0.0 though.

**Comment by noniq** [comment]
Is there something that should be done? Or can this issue be closed?

**Comment by olhor** [comment]
Probably backward compatibility won't be implemented so closing this...
