### ISSUE TITLE
Address dependabot security vulneratbilities

### ISSUE THREAD

**Issue by straydogstudio** [caxlsx/caxlsx#61]
We should address these vulnerabilities (kramdown, rake, json):

https://github.com/caxlsx/caxlsx/network/alerts

I've made the suggested changes, updated gems, and run tests. Everything works. I'm inclined to submit it to the repo after the next release, which should be soon. Incompatibilities during use would then have some time to show up.

**Comment by noniq** [comment]
Oops sorry, I had completely forgotten that you already started to work on this :-(

I just pushed 46215488 which updates the version requirement for kramdown. Because kramdown is used only for generating the documentation, but not in the gem itself, it should be a safe bet. I also ran `yardoc --one-file` before and after the change and compared the outputs: They were identical (except for the timestamp).

As for the two alerts regarding rake and json: If I understand correctly both alerts are only valid if the gem is used with Ruby  < 2, and I don't think we actually support this. Or do we? 🤔   For now I dismissed these alerts with “this code is not actually run”.

**Comment by straydogstudio** [comment]
No worries @noniq I was thinking this probably should be pushed through anyway.

**Comment by kiskoza** [comment]
We could safely remove the [Ruby < 2](https://github.com/caxlsx/caxlsx/blob/462154889855876cc726abae3a4d71e5948d32e1/Gemfile#L5-L8) parts from the Gemfile, because the gemspec requires [ruby '~> 2.3'](https://github.com/caxlsx/caxlsx/blob/462154889855876cc726abae3a4d71e5948d32e1/axlsx.gemspec#L27)

**Comment by noniq** [comment]
Good catch, @kiskoza! Done in e4aeec68.
